const constants = {
    ADD_TO_CART: "ADD_TO_CART",
    REMOVE_FROM_CART: "REMOVE_FROM_CART",
    CLICK_ON_PRODUCT_PREVIEW: "CLICK_ON_PRODUCT_PREVIEW",
    SEARCH_PRODUCT: "SEARCH_PRODUCT",
    SORT_PRODUCTS: "SORT_PRODUCTS",
    SORTED_BY_PRICE: "SORTED_BY_PRICE",
    SORTED_BY_TITLE: "SORTED_BY_TITLE",
    SORTED_BY_WARRANTY: "SORTED_BY_WARRANTY",
    CHANGE_PRODUCT_QUANTITY: "CHANGE_PRODUCT_QUANTITY", 
    // OPEN_MODAL: "OPEN_MODAL",
    // CLICK_ON_PRODUCT_LINK: "CLICK_ON_PRODUCT_LINK",
    CLICK_ON_GO_TO_CART: "CLICK_ON_GO_TO_CART",
    CLOSE_MODAL: "CLOSE_MODAL",
}

export default constants